project:
  type: website
  output-dir: _site

website:
  title: "Dr. Sonali Sharma"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/sonalispatial18/lidar-portfolio

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
  enabled: false

jupyter: false