name: lidar-portfolio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - rasterio
  - geopandas
  - laspy
  - scikit-image
  - matplotlib
  - pandas
  - jupyterlab
  - pip
  - pip:
    - geoai